server:
  port: 8068
  servlet:
    context-path: /bzhi2Auth
spring:
  application:
    name: bzhi2AuthService
logging:
  config: classpath:logback-spring.xml
  file:
    # 根据线上部署的环境进行修改的
    path: D:\project\JavaProjectNew\MonsterProj\serverlog
